---
- name: Add WebUpd8 PPA
  apt_repository:
    repo='ppa:webupd8team/java'
    state=present
    update_cache=yes
  become: yes

- name: Accept Oracle license
  debconf:
    name={{ oraclejdk_package }}
    question=shared/accepted-oracle-license-v1-1
    vtype=select
    value=true
  become: yes

- name: Install OracleJDK package
  apt:
    name={{ oraclejdk_package }}
    state=present
  become: yes

- name: Install OracleJDK JCE Unlimited
  apt:
    name={{ oraclejdk_jce_package }}
    state=present
  when: oraclejdk_install_jce
  become: yes

- name: Set default JDK
  apt:
    name={{ oraclejdk_package | regex_replace('^.*([0-9]).*$', 'oracle-java\\1-set-default') }}
    state=present
  when: oraclejdk_set_as_default
  become: yes

- name: Get JAVA_HOME var from login shell
  command: /bin/sh -l -c "echo $JAVA_HOME"
  register: env_o

- name: Set JAVA_HOME ansible var
  set_fact: oraclejdk_java_home={{ env_o.stdout }}

- name: Use /dev/urandom for Java random source
  lineinfile:
    dest={{ oraclejdk_java_home }}/jre/lib/security/java.security
    regexp="^\s*securerandom.source"
    line="securerandom.source=file:/dev/urandom"
  when: oraclejdk_set_urandom
  become: yes
